version: '3'

services:
        matomo_dbos:
                image: mysql:5.7
                volumes: 
                        - mysql_storage_matomo_compose:/var/lib/mysql
                restart: always
                environment: 
                        MYSQL_ROOT_PASSWORD: rootpass
                        MYSQL_USER: kartikay
                        MYSQL_PASSWORD: redhat
                        MYSQL_DATABASE: matomo
        matomo_os:
                image: matomo
                restart: always
                depends_on:
                        - matomo_dbos
                ports:
                        - "8081:80"
                volumes:
                        - matomo_storage_compose:/var/www/html
                environment:
                        MATOMO_DB_HOST: matomo_dbos
                        MATOMO_DB_USER: kartikay
                        MATOMO_DB_PASSWORD: redhat
                        MATOMO_DB_NAME: matomo

volumes:
        mysql_storage_matomo_compose:
        matomo_storage_compose:
